# Generated by Django 2.1.7 on 2019-02-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_answer_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
